server:
  port: 8200
spring:
  datasource:
    url: jdbc:mysql://192.168.31.129:3306/mydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    schema: classpath:department.sql
    #数据库已经存在department表了，不需要再次执行ddl-schema.sql
    initialization-mode: never
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    maxActive: 20
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    ##   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    spring.datasource.filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:500

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml